# fly.toml app configuration file generated for alice-utils on 2023-11-25T10:22:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alice-utils"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 4040
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
